### PR TITLE
fix errors

### PR DESCRIPTION
**Pull request by Enhex**
fixed errors i got when trying to build with Godot's master branch.

### CODE REVIEW

**Comment by aaronfranke** [comment]
@Enhex When I try to build the module with this PR on the latest Godot master, I get errors about undefined symbols. I get errors on Linux with GCC, Linux with Clang, and macOS with Clang.

```
[ 96%] Linking Program bin/godot.macos.opt.tools.arm64 ...
[100%] progress_finish(["progress_finish"], [])
[100%] Undefined symbols for architecture arm64:
  "Error Node::rpc_id<Vector<Variant> >(int, StringName const&, Vector<Variant>)", referenced from:
      ServerSynchronizer::process_snapshot_notificator(float) in libmodule_network_synchronizer.macos.opt.tools.arm64.a(scene_synchronizer.macos.opt.tools.arm64.o)
  "Error Node::rpc_id<Vector<unsigned char> >(int, StringName const&, Vector<unsigned char>)", referenced from:
      ServerController::doll_sync(float) in libmodule_network_synchronizer.macos.opt.tools.arm64.a(networked_controller.macos.opt.tools.arm64.o)
      ServerController::adjust_player_tick_rate(float) in libmodule_network_synchronizer.macos.opt.tools.arm64.a(networked_controller.macos.opt.tools.arm64.o)
      PlayerController::send_frame_input_buffer_to_server() in libmodule_network_synchronizer.macos.opt.tools.arm64.a(networked_controller.macos.opt.tools.arm64.o)
  "Error Node::rpc_id<>(int, StringName const&)", referenced from:
      ClientSynchronizer::notify_server_full_snapshot_is_needed() in libmodule_network_synchronizer.macos.opt.tools.arm64.a(scene_synchronizer.macos.opt.tools.arm64.o)
  "Error Node::rpc_id<bool>(int, StringName const&, bool)", referenced from:
      SceneSynchronizer::set_enabled(bool) in libmodule_network_synchronizer.macos.opt.tools.arm64.a(scene_synchronizer.macos.opt.tools.arm64.o)
      SceneSynchronizer::set_peer_networking_enable(int, bool) in libmodule_network_synchronizer.macos.opt.tools.arm64.a(scene_synchronizer.macos.opt.tools.arm64.o)
      NetworkedController::set_server_controlled(bool) in libmodule_network_synchronizer.macos.opt.tools.arm64.a(networked_controller.macos.opt.tools.arm64.o)
  "Error Node::rpc_id<unsigned int>(int, StringName const&, unsigned int)", referenced from:
      NetworkedController::set_doll_peer_active(int, bool) in libmodule_network_synchronizer.macos.opt.tools.arm64.a(networked_controller.macos.opt.tools.arm64.o)
      NetworkedController::pause_notify_dolls() in libmodule_network_synchronizer.macos.opt.tools.arm64.a(networked_controller.macos.opt.tools.arm64.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Enhex** [comment]
im getting the same errors, couldn't figure out why.

**Comment by Enhex** [comment]
errors are now gone, after https://github.com/godotengine/godot/pull/63820 got merged.

**Review by aaronfranke — APPROVED** [review]
@Enhex Indeed, I can confirm that this PR works as expected when using master after that PR is merged. @AndreaCatania Please review this PR, we need it downstream, we can merge separately but I'd rather keep things in sync with here whenever possible.

**Comment by AndreaCatania** [comment]
For some reasons I keep not receiving emails unless I got mentioned on this repo, anyway! It looks good thanks!!

**Pull request merged**
